name: personal-blog
region: nyc
domains:
  - domain: backpropagation.ai
    type: PRIMARY
static_sites:
  - name: personal-blog
    git:
      repo_clone_url: https://github.com/dendisuhubdy/personal-blog.git
      branch: main
    build_command: pnpm install && pnpm run build
    output_dir: dist
    environment_slug: node-js
