name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Trigger deployment
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
